# Generated by Django 3.2.23 on 2024-02-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bankreader", "0003_transaction_account_statement_cleanup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="recipient_description",
            field=models.CharField(default="", max_length=256, verbose_name="description for recipient"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="remote_account_name",
            field=models.CharField(default="", max_length=128, verbose_name="remote account name"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="remote_account_number",
            field=models.CharField(default="", max_length=64, verbose_name="remote account number"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="sender_description",
            field=models.CharField(default="", max_length=256, verbose_name="description for sender"),
        ),
    ]
